Update imageMapster.js
ctsit/imagemap pull request #78
Opened 2024-06-11 14:37 UTC by dhinostroza

Second try

2024-06-12 17:42 UTC, saipavan10-git submitted a review, later dismissed
The security scanner shows no problems, as the PSALM no longer complains about javascript eval()(Mentioned by @ChemiKyle on #71 ).  

![image](https://github.com/ctsit/imagemap/assets/32958525/2800fbdc-cd1f-4cd0-a7e0-c569aa2ff860)

Upon further inspection of the change, I noticed that `eval()` was still used in the `imageMapster.js` 

![image](https://github.com/ctsit/imagemap/assets/32958525/6307b0c5-3ecc-4c52-97ab-75822a301828)

@dhinostroza, could you please make the necessary changes to remove or replace `eval()`?


@pbchase The issue we had yesterday was because the PR branch did not have the latest changes from `develop`, this has been resolved with a merge commit.

2024-06-12 18:49 UTC, saipavan10-git requested changes
Requested some changes. Please take a look at the above comment.

2024-06-12 19:06 UTC, dhinostroza commented
@saipavan10-git,
Sorry, I was just following Andy's suggestion on how to replace the file.
Best,
Daniel

On Wed, Jun 12, 2024, 1:49 PM Sai Pavan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Requested some changes. Please take a look at the above comment.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ctsit/imagemap/pull/78#pullrequestreview-2113890550>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEOTI5A647URCTJX3ULRURDZHCJ5DAVCNFSM6AAAAABJEPR2IOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMJTHA4TANJVGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-03-27 12:16 UTC, stingray2772 commented
Is this still in progress? Any ETA?

2025-07-16 15:51 UTC, pbchase commented
Addressed by PR #85

2025-07-16 15:51 UTC, closed without merging